Development
Arturo-M12/Hardlus-Freight-Frenzy pull request #3
Opened 2021-10-22 02:54 UTC by Arturo-M12

Se agregaron los nombres de los motores y el multiplicador.

2021-10-22 16:10 UTC, DiegoMont commented on teamcode/robot/ChasisOmni.java
> +        // TODO: Include multiplier somewhere to increase or decrease the speed of the robot
Una ves que terminen de hacer los TODOs, borren el comentario

2021-10-22 16:13 UTC, DiegoMont commented on teamcode/robot/ChasisOmni.java
> +        double backRightPower = (drive + lateral - turn)*multiplier;
No dejen el código tan apretado. Solo agreguen un espacio entre los operadores. Ejemplo:
`double backRightPower = (drive + lateral - turn) * multiplier;`

2021-10-22 16:13 UTC, DiegoMont requested changes
Revisen los comentarios que dejé y hagan los cambios

2021-10-22 17:13 UTC, Arturo-M12 commented
Creo que ya quedaron los cambios.

2021-10-22 21:59 UTC, DiegoMont approved these changes
Listo

2021-10-23 13:06 UTC, ErnoMitrovic approved these changes
Excelente

2021-10-23 14:27 UTC, merged